### ISSUE TITLE
Add zoom and use functions

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#103]
I don't have a very good feel for these yet, but they came up in some code I was porting from `lens`.

**Comment by arybczak** [comment]
#113 defined `use` in a way such that it works as both `use` and `preuse` from the lens library.

In theory if we make gview return multiple results with folds and traversals, we can also make it work like `ipreuse` and `iuse` from lens (well, actually better, because it won't return monoidal summary of indices when used with indexed fold, which as the lens library highlights doesn't make sense).

Alternative is to have all of these variations explicit (which I guess is consistent with view/preview/toListOf family). @adamgundry what do you think?

I'm not sure how `zoom` fits into the picture, but if it won't need `gview`, we can merge parts of ViewableOptic into `PermeableOptic` and get rid of `gview` entirely. But maybe it's alright to keep it... Ahh, so many questions.
