### ISSUE TITLE
Have something equivalent to generic-lens / make use of overloaded labels

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#11]

**Comment by phadej** [comment]
Because `Optic` is a newtype we can port most of `generic-lens` (which use profunctor encoding internally, so it's not even that difficult; I made a PoC; it's really possible).

I was going to write about ambiguity (do you want `Lens` or `Prism`), but Csongor already did wrote in http://hackage.haskell.org/package/generic-lens-1.1.0.0/docs/Data-Generics-Labels.html

It's tempting to add `Iso` when constructor (or field) are unique; but I don't think it's worth the complexity.

**Comment by arybczak** [comment]
See #121. Do we want to have it? Perhaps not into optics-core, but in general.

Btw, the implementation of labels is nice in a sense that when https://ghc.haskell.org/trac/ghc/ticket/16232 is done, we can replace generic-lens code for type-preserving lenses with the HasField stuff to save compilation time in the majority of cases.

**Comment by phadej** [comment]
`HasField` would miss type-changing lens, which `generic-lens` can do.

**Comment by arybczak** [comment]
Correct, but if you take a look at https://github.com/well-typed/optics/pull/121/files#diff-7b8ab1c103b1a0f0ebb21ea2bfd0ca00R150, there is a separate case for type-preserving lens. And in this case we can use HasField, whereas the general one can be left as-is.
