### ISSUE TITLE
Is it worth keeping toLens etc.?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#146]
We currently define lots of type-restricted synonyms of `castOptic` such as
```hs
toLens :: Is k A_Lens => Optic k is s t a b -> Optic A_Lens is s t a b
toLens = castOptic
```
but I'm wondering if they are really worthwhile. One can always use `castOptic @_ @A_Lens` instead. In practice it should be uncommon to need explicit casts, and if one is required `castOptic` will probably work without explicit type arguments in most cases.

**Comment by arybczak** [comment]
In my experience you need explicit casts in two cases.
1) E.g. you might want to manually define `LabelOptic A_Lens T T T T` instance, but `labelOptic` can then be `equality`, so you need to wrap it in `toLens`. Though when both source and target optic is known, you can use castOptic and it'll just work.

2) In https://github.com/well-typed/optics/blob/003beec60ce7bb4af4f9944a4047e50cb1cfc1f2/optics-extra/src/Optics/Extra/Internal/Zoom.hs#L61-L70
you need to call `toAffineTraversal` before calling `traverseOf`, because otherwise GHC can't figure out that `Is k An_AffineTraversal` implies `Is k A_Traversal` which `traverseOf` expects. In this case you can also use `castOptic`, though you need to explicitly pass the target flavour type.

I think we could remove these functions, though then I would argue that in `castOptic` the target flavour should be the first type parameter so that we can just write `castOptic @A_Lens` instead of `castOptic @_ @A_Lens`.
