### ISSUE TITLE
Raise minimum version for unordered-containers dependency

### ISSUE THREAD

**Issue by Topsii** [well-typed/optics#150]
In `optics-extra` the minimum version required for the `unordered-containers` dependency is 0.2.6
https://github.com/well-typed/optics/blob/388a400214968ab2278ecc3e64a52bfaabacd6a1/optics-extra/optics-extra.cabal#L28

However you are using the function `alterF` which was introduced in `unordered-containers-0.2.10`
https://github.com/well-typed/optics/blob/388a400214968ab2278ecc3e64a52bfaabacd6a1/optics-extra/src/Optics/At.hs#L138

I suggest raising the minimum version for `unordered-containers` to 0.2.10

**Comment by arybczak** [comment]
We do have an `ifdef` around usage of `alterF`:

https://github.com/well-typed/optics/blob/388a400214968ab2278ecc3e64a52bfaabacd6a1/optics-extra/src/Optics/At.hs#L136-L146

But indeed it looks like it's only available from 0.2.10 onwards (even though that's not what https://hackage.haskell.org/package/unordered-containers-0.2.10.0/docs/Data-HashMap-Strict.html#v:alterF says).

Thanks for the catch, fixed in 8002e69.
