### ISSUE TITLE
Diagrams of parts of subtype hierarchy

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#158]
We could consider making additional versions of the [nice diagram](https://github.com/well-typed/optics/blob/master/optics/optics.png), one for each optic kind, that highlights that kind and shows its subtypes and supertypes. These could then be included in the subtyping section of the per-kind pages.

**Comment by arybczak** [comment]
Sounds like a good idea :+1:

**Comment by arybczak** [comment]
Something like this?

![lens](https://user-images.githubusercontent.com/387658/58644171-04c90680-8301-11e9-84d8-be68e7e725cd.png)

**Comment by adamgundry** [comment]
Lovely. I can live with a mixture of graphviz and metapost diagrams, I guess, if it makes things easier. I think we should be consistent with the direction of arrows in the other diagrams, though, i.e. have `Iso` at the bottom?

I'm wondering whether it is better to leave out the optic kinds that are neither subtypes nor supertypes of the kind in focus, i.e. keep `Iso` but drop the other grey kinds?

**Comment by arybczak** [comment]
> I can live with a mixture of graphviz and metapost diagrams, I guess, if it makes things easier.

Indeed. We can convert to metapost later, but graphviz is a lot better for getting things out quickly ;)

We can revert the diagram, sure.

I think leaving all kinds makes for a clearer presentation, especially since the diagram is quite condensed as it is. Grey could be a bit lighter perhaps, but having the whole hierarchy looks good to me.
