### ISSUE TITLE
Separate library for indexed profunctor optics?

### ISSUE THREAD

**Issue by adamgundry** [well-typed/optics#247]
Would it be worth moving some of the "internal implementation details" of `optics-core` into a separate package for indexed profunctor optics? This has been requested at https://www.reddit.com/r/haskell/comments/cyo4o2/welltyped_announcing_the_optics_library/ez73jei/ and also in discussons with @kcsongor it might be useful for `generic-(lens|optics)`.

**Comment by arybczak** [comment]
Well, we could have bare indexed profunctor optics api and then newtype'd api, but

1) It's a lot of work to do (and maintain?).
2) Internals are already exposed, so experimentation is easy (apart from trying to look after new optic kinds, but this is a rare enough case that cloning a repo and working with it won't ruin anyone's day)

In other words, I think the ratio of gains to work necessary is so small it's not worth it.

**Comment by adamgundry** [comment]
I've been discussing this more with @kcsongor and @phadej, and think it would be useful to separate out a bare indexed profunctor optics library, as both `generic-lens` and `optics-core` could then depend on it. The package structure would look something like this:
 * `indexed-profunctor-optics` (name TBC): just the bare profunctor classes/types/limited API
 * `optics-core`: depends on `indexed-profunctor-optics`
 * `generic-lens-core`: depends on `indexed-profunctor-optics`, implements generic optic generation for the bare representation
 * `generic-lens`: depends on `generic-lens-core` (and other stuff) to convert the bare representation to van Laarhoven optics
 * `generic-optics`: depends on `generic-lens-core` and `optics-core` to convert the bare representation to `Optic`

This would save `generic-lens` needing its own internal profunctor optics types, and would make `generic-optics` conversions to `Optic` cheap, while not much changes for the conversions to van Laarvhoven. The plan would be to make the bare library fairly minimal and hopefully not requiring much maintenance; it wouldn't provide a full suite of combinators for bare profunctor optics (though someone could add that in yet another package if they wanted to).

@arybczak is this making sense to you? I can have a go at factoring out the relevant package to make this more concrete.

See also kcsongor/generic-lens#82.

**Comment by arybczak** [comment]
It makes sense, just note that

> would make generic-optics conversions to Optic cheap

I'm not sure if this works, because in my experience in order to optimize away generic representation a concrete profunctor needs to be picked at some point, which amounts to reinterpretation of an optic.

See https://github.com/well-typed/optics/pull/121/files#diff-c89881e2a9bd88b5fdead0b10cbe860fR11

So there shouldn't be much of a difference between
1. converting from profunctor encoding to profunctor encoding and 
2. converting from profunctor encoding to VL encoding, then wrapping the result in `linear`.

**Comment by adamgundry** [comment]
The point is that `generic-optics` would literally just apply the `Optic` newtype wrapper to the bare representation produced by `generic-lens-core`, rather than needing to convert between different profunctor encodings.

**Comment by arybczak** [comment]
Yes, but you have to do that anyway (except you'd be converting between the same representation) if you want generics to be optimized away.

**Comment by kcsongor** [comment]
@arybczak that's right, there needs to be a normalisation step at the end, but we currently think that it should be enough to do it once, rather than twice. The other advantage of having indexed profunctors in a separate package is that they could then be used as the basis for a frontend-agnostic generic derivation library, without incurring a dependency on `profunctor`.

**Comment by adamgundry** [comment]
I've published https://hackage.haskell.org/package/indexed-profunctors-0.1
