### ISSUE TITLE
Deprecate and remove makeFields/makeClassy

### ISSUE THREAD

**Issue by arybczak** [well-typed/optics#315]
There are currently 4 ways to generate field optics (regular functions, labels, `Has*`, classy), which is incredibly confusing.

Also:
- `makeFields` is outright broken as it requires tight coupling between all data types and there is no possibility for ecosystem consistency
- `makeClassy` is weird, I'm not sure what its pros are. It won't allow prefixless fields for multiple data types. Easy to export lenses for a data type and define transitive optics? The first is a non-issue with labels, second one is IMO not enough to keep it.

We should keep only "classic" fields-as-functions (i.e. `makeLenses` family) and if one wants fancy stuff, labels are the way to go.

Doing this will tidy `Optics.TH` module (huge for non-experts), but also simplify the internals.

**Comment by phadej** [comment]
`makeFields` is the driver for from `lens` migration. I don't think we can just drop it. It would make migrations harder to do in pieces. So is `makeClassy`.

**Comment by arybczak** [comment]
I'm for extracting it to `optics-th-compat` and then never looking at it again ;)

**Comment by arybczak** [comment]
But to be fair, if someone wants to migrate in the future, they can migrate to older version of `optics` and then upgrade :thinking:

**Comment by phadej** [comment]
If people migrate to GHC-8.10 first :thinking: they couldn't use older `optics`. Maybe they need stuff from newer `optics`.

I also say in https://oleg.fi/gists/posts/2020-01-25-case-study-migration-from-lens-to-optics.html

> It's worth mentioning that the most tricky issues were inside the auxiliary libraries. The core domain logic, with types which had optics build with `makeLenses` require mostly only changing `.` to `%`.

---

I'm not aware of any "non-maintainer" of `optics` using `optics`, so making migration story in any way more complicated *is too early*.

---

What you mean by

> `makeFields` is outright broken as it requires tight coupling between all data types and there is no possibility for ecosystem consistency

What's broken? What consistency?

**Comment by arybczak** [comment]
`makeFields` needs to have a `HasX` class in scope in other to not generate it, so if you're using it in your application, you either need to:
- put all your data types in one place, or
- have a top level module with hand-written `HasX` classes for every field name you're using.

Both solutions are terrible.

If you lift it to a library level, it becomes even more broken as multiple libraries using it would give you multiple incompatible `HasX` classes for a given `X`. A `top-level` library with `HasX` classes is impossible.

It also doesn't support type-changing updates (neither does `makeClassy`).

Also none of them give you jump-to-definition with `hasktags` or similar.

Labels with `noPrefixFieldLabels` fix all of these. They give you:
1) No data coupling
2) Type-changing updates
3) Prefixless fields
4) Working jump-to-definition

**Comment by phadej** [comment]
I'm very sorry, I confused `makeFields` with `makeLenses`.... I'm confused that there are `makeFields` and `makeClassy`, it shows that I never used them.

**Comment by adamgundry** [comment]
I'd definitely like to see `Optics.TH` documentation improved and have it point beginners in one or two directions rather than four. :wink: Thus I'm moderately sympathetic to the idea that we should deprecate `makeFields` and `makeClassy` in favour of `makeFieldLabels`, although I agree that we should keep them around as a migration aid for the time being.

That said, it's not clear that the multiple incompatible `HasX` classes of `makeFields` are entirely a bad thing. One argument people bring up against `HasField`, and I think the same applies to `LabelOptic`, is that it is somewhat "stringly-typed": in particular, just because two datatypes have a field of the same name, it doesn't necessarily follow that those fields are semantically equivalent. So one could argue that using `makeFields` you can decide whether to share a common `HasX` class (by importing it) or to have separate classes. IMHO this argument merely shows that one shouldn't design an API that is polymorphic in `HasField`/`LabelOptic` constraints, and I think it is fine to use them for type-directed name resolution locally, but there's definitely a debate to be had.

**Comment by arybczak** [comment]
This was (at least partially) done in #326.

At this point I agree that removal is probably too harsh and even moving the code to something like `optics-th-compat` doesn't buy us much. The code might be made simpler, but that's it (and the code is alright to work with).
