### ISSUE TITLE
template-haskell-optics release/maintenance?

### ISSUE THREAD

**Issue by patrickt** [well-typed/optics#337]
Hey there 👋 I noticed that the template-haskell-optics wasn’t on Hackage, and that you’re looking for maintainers to manage it. I’d like to use the package in https://github.com/fused-effects/fused-effects-th, so I’m happy to take on the maintenance if it means that a Hackage release would be possible. Let me know!

**Comment by arybczak** [comment]
Hey, sure, thanks for offering that :)

AFAIK the only thing needed before the release is https://github.com/well-typed/optics/issues/252 which amounts to porting a fairly trivial PR from `lens`.

Maintenance then would mean most of the time porting other changes from `lens` (usually on the release of new GHC version) ;)

For starters you can send a PR that fixes the above issue so we can get the release out :)

I'm not sure whether it's better to move `template-haskell-optics` to a separate repo or keep it here and accept PRs. @adamgundry @phadej thoughts?

**Comment by adamgundry** [comment]
Indeed, thanks for volunteering to help out!

I had a brief look and it turns out that `template-haskell-optics` is in better shape than I realised, mostly thanks to @arybczak in #246. So yes I think the main outstanding issue is #252; there is still a lurking TODO comment in the haddocks but I think it is now redundant. The lingering obligation will be to support new versions of `template-haskell-optics` when there is a new GHC/`template-haskell` release, but that shouldn't be too much work.

Another question is how `template-haskell-optics` should be versioned/maintained going forward. The approach `lens` takes is to support a range of `template-haskell` versions with CPP, but this means the exposed API depends on the `template-haskell` version being used. To avoid this and the CPP, we could consider having a different branch(?)/release of `template-haskell-optics` for each version of `template-haskell`. Or is that too much busywork and too painful for CI?

> I'm not sure whether it's better to move `template-haskell-optics` to a separate repo or keep it here and accept PRs.

I'd be inclined to keep it here for the time being, at least I don't yet see a particular need to move it.

**Comment by phadej** [comment]
> I'd be inclined to keep it here for the time being, at least I don't yet see a particular need to move it.

Adding support for new GHCs won't be blocked on updating that (somewhat massive) package.

**Comment by arybczak** [comment]
@patrickt I checked diff between `Language.Haskell.TH.Optics` and `Language.Haskell.TH.Lens` and it turns out there is one more divergence that needs to be bridged (#345). Similarly easy to #252 though.

**Comment by arybczak** [comment]
I created #347 with a few polishing bits, once it's merged we can make a release :tada:

**Comment by arybczak** [comment]
I'll merge and release template-haskell-optics-0.1 during the weekend unless anyone objects.

**Comment by arybczak** [comment]
https://hackage.haskell.org/package/template-haskell-optics-0.1

**Comment by patrickt** [comment]
Thank you so much, @arybczak!

**Comment by adamgundry** [comment]
Yes, thanks @arybczak! I've been distracted by ICFP, hence the radio silence for a bit, but I'm happy to see this move forward.
