### ISSUE TITLE
optics-0.4 release

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#375]
I'm very eager to use `indexed-traversable`.

I haven't followed the `LabelOptic` changes, is the #365 only things left?

Does @adamgundry or @arybczak have some breaking changes in mind, which would be great to get in?

I think it would be great to have GHC-9.0 compatible release as soon as it is released, so that could be a (soft) deadline for `optics-0.4`.

**Comment by arybczak** [comment]
Apart from #365 I need to port a bit from https://github.com/ekmett/lens/pull/945. Other than that I think it's good to go.

**Comment by adamgundry** [comment]
Sorry, I haven't been keeping up because of "holidays", but I'm supportive of releasing `optics-0.4` around the GHC-9.0 release if not before. I'll try to find an opportunity to properly review the recent changes in the next week or so. But I don't have anything that is urgent to land before a release.

**Comment by phadej** [comment]
GHC-9.0 is released.

**Comment by arybczak** [comment]
I suggest merging #399 and getting a release out.

**Comment by adamgundry** [comment]
Sounds good to me!

**Comment by adamgundry** [comment]
We don't have CI for GHC 9.0.1 yet (https://github.com/haskell-CI/haskell-ci/issues/474), but I've verified locally that the main packages build and pass tests. 

Still lacking:
 - [ ] `optics-sop` is blocked by https://github.com/well-typed/generics-sop/issues/130 (but isn't released anyway)
 - [ ] `template-haskell-optics` needs to be amended to support `template-haskell-2.17.0.0`
 - [ ] Benchmarks don't build because of dependency bounds, but they can be persuaded to with enough `allow-newer`.

As far as I can see we need to:
 - [ ] Upload 0.4 releases of `optics-core`, `optics-th`, `optics-extra` and `optics` to Hackage.
 - [ ] Relax the bounds of the released `optics-vl` to permit `optics-core-0.4`.
 - [ ] Add release tag.

I'm going to open a PR with some minor changelog fixes. Provisionally I'm planning to make a release early next week. Anything else we need to do first?

**Comment by adamgundry** [comment]
* https://hackage.haskell.org/package/optics-core-0.4/candidate
* https://hackage.haskell.org/package/optics-extra-0.4/candidate
* https://hackage.haskell.org/package/optics-th-0.4/candidate
* https://hackage.haskell.org/package/optics-0.4/candidate

**Comment by phadej** [comment]
I tested some small developments, and at least `optics-core` package doesn't break anything unexpectedly there

**Comment by adamgundry** [comment]
I've made the release.

**Comment by phadej** [comment]
Hurray!
