### ISSUE TITLE
Please add "construct" as a synonym for "review"

### ISSUE THREAD

**Issue by tomjaguarpaw** [well-typed/optics#420]
`Review` is typically described in a baffling way. `optics` says

> A Review is a backwards Getter, i.e. a Review T B is just a function B -> T.

(`lens` is no better in this regard). But a `Review` is actually simple. It's just constructing a value from a payload! Look:

```
-- >>> review _Left "hi"
-- Left "hi"
```

Surely `construct` would be a much better name for this function.

```
-- >>> construct _Left "hi"
-- Left "hi"
```

That needs no explanation whatsoever! The description "a Review T B is just a function B -> T" suddenly becomes redundant.

I think that adding `construct` as a synonym for `review` would make this aspect of the library *much* more approachable.  `optics` already does a *great* job of making optics approachable. Please let's keep eking out improvements to the user experience where we can. This proposal seems like an easy way of improving the user experience.

**Comment by phadej** [comment]
`review` should be named `build` or `building` (as we have `matching`, which could been `match`). Naming is hard.

I don't really see a point of adding an alias (just) to `review`.

We don't call `view` `get` (but it's an operation of getter), `to` `getter` (because `to` constructs `Getter`, c.f. `lens`) etc.
These inconsistencies are unfortunate, and I don't think that adding aliases here and there really helps.
(I suspect that`view`, `set` and `over` are not named  `get`, `put` and `modify` as `MonadState` has exactly those names in use already).

Writing down a table (like in https://oleg.fi/gists/posts/2017-04-18-glassery.html#contents which is dated) and figuring out good and consistent names would be great, but if we go for it, we should rename things across the library. (I'd be ok with renaming everything, but aliases are not fun as they increase the API and different people start using different names etc.).

---

This is a documentation issue, which is a cause of non-linear reading of things. What `Review` does is probably clearer when you see it as restriction of `Prism` - something you implicitly do in an example.

However, `unto fst` is a valid `Review` too, and it's not injective, i.e. isn't the building part of any `Prism`. That what *"a Review T B is just a function B -> T."* tries to highlight, it's really *any* `B -> T` function.

I also think that trying to learn what different optics are by looking at the documentation of libraries like `optics` and `lens` is wrong. Like trying to understand what Fourier Transform by looking at https://en.wikipedia.org/wiki/Fourier_transform#Tables_of_important_Fourier_transforms tables. Sadly there is no good (and free) "text book" about lens and optics.

**Comment by arybczak** [comment]
I'm with @phadej on that one.

Review actually is just a reversed Getter, it's clear once you take a look at this diagram for what `re` does to optics:

![re](https://raw.githubusercontent.com/well-typed/optics/7cc3f9c334cdf69feaf10f58b11d3dbe2f98812c/optics/diagrams/reoptics.png)

To make things consistent either `Review` would need to be renamed to `ReversedGetter` or `Getter` would have to become `View`, neither of which helps a lot.

`construct` as a synonym for `review` only makes sense if you think of reviewing a Prism, but when you take a proper `Iso` or a `Review` it's just as confusing.

**Comment by tomjaguarpaw** [comment]
That diagram makes perfect mathematical sense but I don't think it is helpful in the vast majority of practical use cases. My guess is that in the vast majority of practical uses cases a "`Review`" is used to construct.

Anyway, it seems that I should build consensus for this naming scheme elsewhere before coming back to you.
