### ISSUE TITLE
Hide internals in `optics-core`

### ISSUE THREAD

**Issue by phadej** [well-typed/optics#95]
They were exposed to make `generic-optics` Prism derivation.

Would

```haskell
newtype PrismT a b s t = PT { unPT :: Prism a b a b -> Prism s t a b }

instance P.Profunctor (PrismT s t) where
    dimap f g (PT h) = PT ((iso f g %) . h )

instance P.Choice (PrismT s t) where
    right' (PT h) = PT ((_Right %%) . h)

-- /TODO/ optics-core could/should provide a way to 'coerce'
-- arguments of Optic, the arguments are of representational role; morally.
prismVL'
  :: forall s t a b.
     GL.Prism s t a b
  -> Prism    s t a b
prismVL' f = prism runIdentity Right %% o %% prism Identity Right
  where 
    o :: Prism s (Identity t) a (Identity b)
    o = unPT (f (PT id)) (castOptic equality)
```

be ok for now. It's not optimal, but good enough. Also soon `generic-lens` would (in a way or another) expose profunctor optics interface, so we can drop `prism runidentity Right % _ % prism Identity Right`

**Comment by arybczak** [comment]
The adaptation is much more involved than what I provided in #92.

You're trying to jump through hoops to hide the internals (which will not work BTW as indexed Functor/Foldable/Traversable need internals too and we're going to move them out of optics-core).

By wanting to hide the internals you'll make everyone jump through hoops too (as I wrote in #86).

Playing devil's advocate, someone wrote a blog post where he argues that exposing internal modules is a bad idea: https://www.reddit.com/r/haskell/comments/a0ioo3/internal_convention_is_a_mistake/

Reddit thread has some good arguments why that doesn't work very well, most of them I enlisted in #89.

Funnily enough, I was once looking for database libraries and were checking out hasql (which is written by the author of the above blog post). It had some weird restrictions at the time and it didn't expose internal modules to quickly amend the situation. You know what I did? I didn't even consider this library further because I know how annoying it is to have to deal with libraries that try to protect you from yourself by hiding internals.

Here's a complaint about internal modules from Edward Kmett: https://www.reddit.com/r/haskell/comments/2uoton/edward_kmett_encapsulation_vs_code_reuse/

**Comment by arybczak** [comment]
> Also soon `generic-lens` would (in a way or another) expose profunctor optics interface, so we can drop `prism runidentity Right % _ % prism Identity Right`

Here's another live example why hiding internals is not a good idea. If it wasn't hidden, we'd just use the representation. Instead we jump though hoops and hope that author of `generic-lens` will be kind enough to do that soon (and in this case he might as well do, but in general relying on people doing things fast in open source space simply doesn't work).

**Comment by adamgundry** [comment]
I tend to agree with @arybczak here. I don't see much harm in exposing the internal modules from `optics-core` provided they are appropriately named/documented, and it avoids the need to try to forsee all possible reasons for accessing the internals. They shouldn't be re-exported from the main `optics` module, of course.

**Comment by adamgundry** [comment]
We should have a better story for `coerce`, indeed. Worth making a separate issue?

I agree that if anything actually needs access to the internals, we should try to figure out a good public API for use instead (maybe excluding things that are morally almost part of `optics-core` anyway). But we can do that even if internals are exposed. I guess there is always the temptation to just depend on the internal module and move on, but on balance I think it's better to accept that cost than to simply prohibit such things without patching the library.

**Comment by arybczak** [comment]
Another point for the story of not hiding internals: https://pl.reddit.com/r/haskell/comments/83qcak/haskell_needs_better_libraries_a_proposal/dvp0jc1/

Closing for now, I think it's clear we don't want to do it.
